src/views/auth_view.py
from flask import Blueprint, render_template, redirect, url_for, request
from facades.auth_facade import AuthFacade
from models.client_errors import ValidationError, AuthError

auth_blueprint = Blueprint("auth_view", __name__)

facade = AuthFacade()

@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    try:
        if request.method == "GET": return render_template("register.html", user = {})
        facade.register()
        return redirect(url_for("home_view.home"))
    except ValidationError as err:
        return render_template("register.html", error = err, user = err.model)
    
@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    try:
        if request.method == "GET":
            err = request.args.get("error")
            return render_template("login.html", error = err, credentials = {})
        facade.login()
        return redirect(url_for("home_view.home"))
    except (ValidationError, AuthError) as err:
        return render_template("login.html", error = err.message, credentials = err.model)
    
@auth_blueprint.route("/logout")
def logout():
    facade.logout()
    return redirect(url_for("home_view.home"))

src/views/employees_view.py
from flask import Blueprint, render_template, send_file, request, url_for, redirect
from facades.employee_facade import EmployeeFacade
from facades.auth_facade import AuthFacade
from utils.image_handler import ImageHandler
import json
from models.client_errors import ResourceNotFound, ValidationError, AuthError

employees_blueprint = Blueprint("employees_view", __name__)

employee_facade = EmployeeFacade()
auth_facade = AuthFacade()

@employees_blueprint.route("/employees")
def employees_list():
    all_employees = employee_facade.get_all_employees()
    return render_template("all_employees.html", employees = all_employees, active = "our_employees")

@employees_blueprint.route("/employees/<int:id>")
def one_employee(id):
    try:
        next_id = employee_facade.get_next_employee_id(id)
        previous_id = employee_facade.get_previous_employee_id(id)
        one_employee = employee_facade.get_one_employee(id)
        return render_template("employee.html", employee = one_employee, next_id = next_id, previous_id = previous_id)
    except ResourceNotFound as err:
        return render_template("404.html", error = err.message)

@employees_blueprint.route("/employees/images/<string:image_name>")
def get_image(image_name):
    image_path = ImageHandler.get_image_path(image_name)
    return send_file(image_path)

@employees_blueprint.route("/employees/add", methods=['GET', 'POST'])
def insert():
    try:
        auth_facade.block_anonymous()
        if request.method == "GET":
            all_countries = employee_facade.get_all_countries() 
            all_cities = employee_facade.get_all_cities()
            cities_json = json.dumps([city.__dict__ for city in all_cities])
            return render_template('add_employee.html', countries = all_countries, cities_json = cities_json, active = "add_employee")
        employee_facade.add_employee()
        return redirect(url_for('employees_view.employees_list'))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    except ValidationError as err:
        all_countries = employee_facade.get_all_countries() 
        all_cities = employee_facade.get_all_cities()
        cities_json = json.dumps([city.__dict__ for city in all_cities])
        return render_template("add_employee.html", countries = all_countries, cities_json = cities_json, error=err.message, active = "add_employee")

@employees_blueprint.route("/employees/edit/<int:id>", methods=['GET', 'POST'])
def edit(id):
    try:
        auth_facade.block_anonymous()
        if request.method == "GET":
            employee = employee_facade.get_one_employee(id)
            all_countries = employee_facade.get_all_countries() 
            all_cities = employee_facade.get_all_cities()
            cities_json = json.dumps([city.__dict__ for city in all_cities])
            return render_template("edit_employee.html", employee = employee, countries = all_countries, cities_json = cities_json)
        employee_facade.update_employee()
        return redirect(url_for("employees_view.one_employee", id=id))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    except ValidationError as err:
        all_countries = employee_facade.get_all_countries() 
        all_cities = employee_facade.get_all_cities()
        cities_json = json.dumps([city.__dict__ for city in all_cities])
        return render_template("edit_employee.html", error = err.message, employee = err.model, countries = all_countries, cities_json = cities_json)

@employees_blueprint.route("/employees/delete/<int:id>")
def delete(id):
    try:
        auth_facade.block_anonymous()
        auth_facade.block_non_admin()   
        employee_facade.delete_employee(id)
        return redirect(url_for("employees_view.employees_list"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))

src/views/home_view.py
from flask import Blueprint, render_template

home_blueprint = Blueprint("home_view", __name__)

@home_blueprint.route("/")
@home_blueprint.route("/home")
def home():
    return render_template("home.html", active = "home")

src/templates/add_employee.html
{% extends "layout.html" %}

{% block title %}
Add a new employee
{% endblock title %}

{% block content %}
<div class="form-container">
    {% if error %}
        <div class="error">
            <p class="error-message">
                {{error}}
            </p>
        </div>
        <hr>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        <label>First Name:</label>
        <input type="text" name="first_name" class="form-control" required minlength="2" maxlength="40">

        <label>Last Name:</label>
        <input type="text" name="last_name" class="form-control" required minlength="2" maxlength="100">

        <label>Title of Courtesy:</label>
        <input type="text" name="title_of_courtesy" class="form-control" required minlength="3" maxlength="100">

        <label>Job Title:</label>
        <input type="text" name="title" class="form-control" required minlength="2" maxlength="150">

        <label>Birth Date:</label>
        <input type="date" name="birth_date" class="form-control" required>

        <label>Hire Date:</label>
        <input type="date" name="hire_date" class="form-control" required>

        <label>Country Name: </label>
        <select class="form-select" name="country_id" id="country" onchange="updateCities()" required>
            <option value="0" disabled selected>Select Country</option>
            {% for country in countries%}
                <option value="{{ country.id }}" data-country-id="{{ country.id }}">{{ country.name }}</option>
            {% endfor %}
        </select>

        <label>City Name: </label>
        <select class="form-select" name="city_id" id="city" data-cities="{{ cities_json }}" required>
            <option value="0" selected disabled>Select City</option>
        </select>

        <label>Address: </label>
        <input type="text" name="address" class="form-control" required minlength="5" maxlength="200">

        <label>Postal Code: </label>
        <input type="text" name="postal_code" class="form-control" required minlength="2" maxlength="20">

        <label>Phone: </label>
        <input type="text" name="phone" class="form-control" required minlength="7" maxlength="20">

        <label>Notes: </label>
        <textarea class="form-control" name="notes" required minlength="5" maxlength="1000"></textarea>

        <label>Add Image: </label>
        <input type="file" name="image" accept="image/*" class="form-control" required>

        <button class="btn btn-primary w-100">Add Employee</button>
    </form>
    
</div>


{% endblock content %}

src/templates/all_employees.html
{% extends "layout.html" %}

{% block title %}
Northwind | Employees
{% endblock title %}

{% block content %}
<div class="table-container">
    <table class="table table-primary table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>Full Name</th>
                <th>Title</th>
                <th>Birth Date</th>
                <th>Country</th>
                <th>City</th>
                <th>Photo</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for e in employees %}
                <tr>
                    <td>
                        <a href="{{ url_for('employees_view.one_employee', id=e.id) }}">
                            {{e.title_of_courtesy}} {{e.first_name}} {{e.last_name}}
                        </a>
                    </td>
                    <td>{{e.title}}</td>
                    <td>{{e.birth_date}}</td>
                    <td>{{e.country_name}}</td>
                    <td>{{e.city_name}}</td>
                    <td>
                        <img src="{{ url_for('employees_view.get_image', image_name = (e.image if e.image else '---')) }}">
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

src/templates/auth.html
<div class="auth">
    {% if user %}
        <span>Hello {{user["first_name"]}} {{user["last_name"]}}</span>
        <span> | </span>
        <a href="{{ url_for('auth_view.logout') }}">Logout</a>

    {% else %}
        <span>Hello Guest</span>
        <span> | </span>
        <a href="{{ url_for('auth_view.login') }}">Login</a>
        <span> | </span>
        <a href="{{ url_for('auth_view.register') }}">Register</a>

    {% endif %}
</div>

src/templates/edit_employee.html
{% extends "layout.html" %}

{% block title %}
Edit {{employee.first_name}} {{employee.last_name}}
{% endblock title %}

{% block content %}

<div class="form-container">
    {% if error %}
        <div class="error">
            <p class="error-message">
                {{error}}
            </p>
        </div>
        <hr>
    {% endif %}
    <form method="post" enctype="multipart/form-data">

        <input type="hidden" name="id" value="{{employee.id}}">

        <label>First Name:</label>
        <input type="text" name="first_name" class="form-control" value="{{employee.first_name}}" required minlength="2" maxlength="40">

        <label>Last Name:</label>
        <input type="text" name="last_name" class="form-control" value="{{employee.last_name}}" required minlength="2" maxlength="100">

        <label>Title of Courtesy:</label>
        <input type="text" name="title_of_courtesy" class="form-control" value="{{employee.title_of_courtesy}}" required minlength="3" maxlength="100">

        <label>Job Title:</label>
        <input type="text" name="title" class="form-control" value="{{employee.title}}" required minlength="2" maxlength="150">

        <label>Birth Date:</label>
        <input type="date" name="birth_date" class="form-control" value="{{employee.birth_date}}" required>

        <label>Hire Date:</label>
        <input type="date" name="hire_date" class="form-control" value="{{employee.hire_date}}" required>

        <label>Country Name: </label>
        <select class="form-select" name="country_id" id="country" onchange="updateCities()" required>
            <option value="0" disabled>Select Country</option>
            <option value="{{employee.country_id}}" selected>{{employee.country_name}}</option>
            {% for country in countries%}
                <option value="{{ country.id }}" data-country-id="{{ country.id }}">{{ country.name }}</option>
            {% endfor %}
        </select>

        <label>City Name: </label>
        <select class="form-select" name="city_id" id="city" data-cities="{{ cities_json }}" required>
            <option value="0" disabled>Select City</option>
            <option value="{{employee.city_id}}" selected>{{employee.city_name}}</option>
        </select>

        <label>Address: </label>
        <input type="text" name="address" class="form-control" value="{{employee.address}}" required minlength="5" maxlength="200">

        <label>Postal Code: </label>
        <input type="text" name="postal_code" class="form-control" value="{{employee.postal_code}}" required minlength="2" maxlength="20">

        <label>Phone: </label>
        <input type="text" name="phone" class="form-control" value="{{employee.phone}}" required minlength="7" maxlength="20">

        <label>Notes: </label>
        <textarea class="form-control" name="notes" required minlength="5" maxlength="1000">{{employee.notes}}</textarea>

        <label>Add Image: </label>
        <input type="file" name="image" accept="image/*" class="form-control">

        <button class="btn btn-primary w-100">Update</button>
    </form>
</div>

{% endblock content %}

src/templates/employee.html
{% extends "layout.html" %}

{% block title %}
{{employee.title_of_courtesy}} {{employee.first_name}} {{employee.last_name}}
{% endblock title %}

{% block content %}
    <div class="employee-card">
        <aside class="employee-image">
            <img src="{{url_for('employees_view.get_image', image_name = (employee.image if employee.image else '---'))}}">
        </aside>
        <main class="employee-details">
            <div class="emp-det-left-container">
                <ul>
                    <li>
                        <span class="category">Full Name:</span>
                        <span>&nbsp;&nbsp;{{employee.title_of_courtesy}} {{employee.first_name}} {{employee.last_name}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">Title:</span>
                        <span>&nbsp;&nbsp;{{employee.title}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">Birth Date:</span>
                        <span>&nbsp;&nbsp;{{employee.birth_date}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">Hire Date:</span>
                        <span>&nbsp;&nbsp;{{employee.hire_date}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">Notes:</span>
                        <span>&nbsp;&nbsp;{{employee.notes}}</span>
                    </li>
                    <hr>
                </ul>
            </div>
            <div>
                <ul>
                    <li>
                        <span class="category">Country Name:</span>
                        <span>&nbsp;&nbsp;{{employee.country_name}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">City Name:</span>
                        <span>&nbsp;&nbsp;{{employee.city_name}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">Address:</span>
                        <span>&nbsp;&nbsp;{{employee.address}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">Postal Code:</span>
                        <span>&nbsp;&nbsp;{{employee.postal_code}}</span>
                    </li>
                    <hr>
                    <li>
                        <span class="category">Phone Number:</span>
                        <span>&nbsp;&nbsp;{{employee.phone}}</span>
                    </li>
                    <hr>
                </ul>
            </div>
        </main>
        <footer>
            <div class="prev-or-next">
                {% if previous_id == None %}
                <a class="btn btn-outline-primary disabled">Previous</a>
                <a class="btn btn-outline-primary" href="{{url_for('employees_view.one_employee', id=next_id)}}">Next</a>
                {% elif next_id == None %}
                <a class="btn btn-outline-primary" href="{{url_for('employees_view.one_employee', id=previous_id)}}">Previous</a>
                <a class="btn btn-outline-primary disabled">Next</a>
                {% else %}
                <a class="btn btn-outline-primary" href="{{url_for('employees_view.one_employee', id=previous_id)}}">Previous</a>
                <a class="btn btn-outline-primary" href="{{url_for('employees_view.one_employee', id=next_id)}}">Next</a>
                {% endif %}
            </div>
            <div class="bottom-buttons">
                <a class="btn btn-dark btn-lg" href="{{ url_for('employees_view.employees_list') }}">Back</a>
                <a class="btn btn-dark btn-lg" href="{{ url_for('employees_view.edit', id = employee.id) }}">Edit</a>
                <a class="btn btn-dark btn-lg" onclick= "confirmDelete()" href="{{ url_for('employees_view.delete', id = employee.id) }}">Delete</a>
            </div>
        </footer>
    </div>
{% endblock content %}

src/templates/home.html
{% extends "layout.html" %}

{% block title %}
Northwind | Home
{% endblock title %}

{% block content %}
    <div class="main-img">
        <img src="{{ url_for('static', filename='images/employees_icon.png')}}">
    </div>
    <div class="main-par">
        <p>
            The Northwind Employees website is a comprehensive portal designed for the staff of Northwind Traders, providing a one-stop solution for all employee-related needs and information. It features a user-friendly interface for accessing personal profiles, company updates, and HR resources. The site also includes tools for project management, team collaboration, and internal communication, fostering a connected and efficient workplace environment. Secure and easily navigable, it's an essential tool for enhancing employee engagement and productivity within Northwind Traders.
        </p>
    </div>
{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for ('static', filename='css/style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
<title>{% block title %}{% endblock title %}</title>
</head>
<body>

    {% set user = session.get("current_user")%}

    <section class="layout">

        <header>
            <h1>Northwind</h1>
            {% include "auth.html" %}
        </header>

        <nav>
            <div>
                <a href="{{ url_for('home_view.home') }}"
                    {% if active=='home'%}
                    class="btn btn-dark btn-lg nav-button static"
                    {% else %}
                    class="btn btn-outline-dark btn-lg nav-button"
                    {% endif %}>
                    Home Page
                </a>
            </div>
            <div>
                    <a href="{{ url_for('employees_view.employees_list') }}" 
                    {% if active=='our_employees'%}
                    class="btn btn-dark btn-lg nav-button static"
                    {% else %}
                    class="btn btn-outline-dark btn-lg nav-button"
                    {% endif %}>
                    Our Employees
                </a>
            </div>

            {% if user %}  
                <div>
                    <a href="{{ url_for('employees_view.insert') }}" 
                        {% if active=='add_employee'%}
                        class="btn btn-dark btn-lg nav-button static"
                        {% else %}
                        class="btn btn-outline-dark btn-lg nav-button"
                        {% endif %}>
                        Add New Employee
                    </a>
                </div>
            {% endif %}

        </nav>

        <main>
            {% block content %}
            {% endblock content %}
        </main>

        <aside>
            <iframe src="https://gifer.com/embed/ICmt" frameBorder="0" allowFullScreen></iframe>
        </aside>

        <footer>
            <div class="footer-container">
                <p>Please consider donating to our website in <a href="#">nivneedsmoney.com</a> 🥰</p>
            </div>
        </footer>

    </section>
</body>
</html>

src/templates/login.html
{% extends "layout.html" %}

{% block title %}
Login
{% endblock title %}

{% block content %}
<div class="form-container">
    {% if error %}
        <div class="error">
            <p class="error-message">
                {{error}}
            </p>
        </div>
        <hr>
    {% endif %}
    <form method="post">

        <label>Email:</label>
        <input type="email" name="email" class="form-control" value="{{credentials.email}}" required minlength="5" maxlength="100">

        <label>Password:</label>
        <input type="password" name="password" class="form-control" value="{{credentials.password}}" required minlength="4" maxlength="100">

        <button class="btn btn-primary w-100 register-btn">Login</button>
    </form>
</div>
{% endblock content %}

src/templates/register.html
{% extends "layout.html" %}

{% block title %}
Register
{% endblock title %}

{% block content %}
<div class="form-container">
    {% if error %}
        <div class="error">
            <p class="error-message">
                {{error}}
            </p>
        </div>
        <hr>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        <label>First Name:</label>
        <input type="text" name="first_name" class="form-control" value="{{user.first_name}}" required minlength="2" maxlength="20">

        <label>Last Name:</label>
        <input type="text" name="last_name" class="form-control" value="{{user.last_name}}" required minlength="2" maxlength="30">

        <label>Email:</label>
        <input type="email" name="email" class="form-control" value="{{user.email}}" required minlength="5" maxlength="100">

        <label>Password:</label>
        <input type="password" name="password" class="form-control" required minlength="4" maxlength="100">

        <button class="btn btn-primary w-100 register-btn">Register</button>
    </form>
</div>
{% endblock content %}